# Secrets!
base_repo:
  name: ''
  access_token: ''

github:
  app_key: ''
  app_secret: ''

session_secret: ''

# Settings
git_data_path: '/home/git'

ssh_authorized_keys: '/home/git/.ssh/authorized_keys'

first_slot_port: 3000

slots:
  - main
  - secondary
